services:
  chatbot:
    build: .
    container_name: financial_chatbot
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_PATH=data/mini_df.csv
      - CHROMA_DB_PATH=./chroma_db
      - COLLECTION_NAME=financial_news
      - EMBEDDING_MODEL=text-embedding-3-small
      - LLM_MODEL=gpt-4.1-mini-2025-04-14
    volumes:
      # Сохраняем ChromaDB данные между запусками
      - chroma_data:/app/chroma_db
      # Монтируем данные (можно заменить на bind mount для обновления данных)
      - ./data:/app/data:ro
      # Монтируем тесты для разработки
      - ./tests:/app/tests:ro
      # Монтируем директорию для результатов тестов
      - ./test_results:/app/test_results
    restart: unless-stopped
    
  # Интерактивный сервис для ручного запуска
  chatbot-interactive:
    build: .
    container_name: financial_chatbot_interactive
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_PATH=data/mini_df.csv
      - CHROMA_DB_PATH=./chroma_db
      - COLLECTION_NAME=financial_news
      - EMBEDDING_MODEL=text-embedding-3-small
      - LLM_MODEL=gpt-4.1-mini-2025-04-14
    volumes:
      - chroma_data:/app/chroma_db
      - ./data:/app/data:ro
      - ./tests:/app/tests:ro
      - ./test_results:/app/test_results
    profiles:
      - interactive

volumes:
  chroma_data:
    driver: local